spring:
  datasource:
    url: jdbc:mysql://localhost/shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: scott
    password: scott
    initialization-mode: always
  jpa.hibernate.ddl-auto: update
server.port: 9001